### ISSUE TITLE
The error descriptions about ASCI Red in file "00-intro-to-cpsc-4770_6770.ipynb"?

### ISSUE THREAD

**Issue by fuqianz** [linhbngo/cpsc-4770_6770#1]
In file "00-intro-to-cpsc-4770_6770.ipynb", the information about ASCI Red, the first supercomputer with speed 1TFLOPS, is not correct. ASCI Red was created by Intel, and taken the 1st place in June 1997 with 1TFLOPS according to the TOP500 supercomputer sites (https://www.top500.org/timeline/). 

Actually, the IBM ASCI White system located at Lawrence Livermore National Laboratory took the No. 1 position in November 2000 with 4.9 teraflop/s Linpack performance.

**Comment by linhbngo** [comment]
Thank you for catching that. I mixed up the ASCI Red with the ASCI White. This has been corrected.
